package cn.ac.lz233.tarnhelm.ui.compose.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFA81898)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD7F1)
val md_theme_light_onPrimaryContainer = Color(0xFF390034)
val md_theme_light_secondary = Color(0xFF78526E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD7F1)
val md_theme_light_onSecondaryContainer = Color(0xFF2E1029)
val md_theme_light_tertiary = Color(0xFF914B2F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBCF)
val md_theme_light_onTertiaryContainer = Color(0xFF380D00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1A1D)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1A1D)
val md_theme_light_surfaceVariant = Color(0xFFEFDEE6)
val md_theme_light_onSurfaceVariant = Color(0xFF4F444A)
val md_theme_light_outline = Color(0xFF80747B)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF342F32)
val md_theme_light_inverseOnSurface = Color(0xFFF8EEF2)
val md_theme_light_inversePrimary = Color(0xFFFFACEA)
val md_theme_light_surfaceTint = Color(0xFFA81898)
val md_theme_light_surfaceTintColor = Color(0xFFA81898)

val md_theme_dark_primary = Color(0xFFFFACEA)
val md_theme_dark_onPrimary = Color(0xFF5D0054)
val md_theme_dark_primaryContainer = Color(0xFF840078)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD7F1)
val md_theme_dark_secondary = Color(0xFFE8B9D9)
val md_theme_dark_onSecondary = Color(0xFF46253F)
val md_theme_dark_secondaryContainer = Color(0xFF5F3B56)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD7F1)
val md_theme_dark_tertiary = Color(0xFFFFB59A)
val md_theme_dark_onTertiary = Color(0xFF571E06)
val md_theme_dark_tertiaryContainer = Color(0xFF74341A)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBCF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1F1A1D)
val md_theme_dark_onBackground = Color(0xFFEAE0E3)
val md_theme_dark_surface = Color(0xFF1F1A1D)
val md_theme_dark_onSurface = Color(0xFFEAE0E3)
val md_theme_dark_surfaceVariant = Color(0xFF4F444A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD2C2CA)
val md_theme_dark_outline = Color(0xFF9B8D95)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFEAE0E3)
val md_theme_dark_inverseOnSurface = Color(0xFF342F32)
val md_theme_dark_inversePrimary = Color(0xFFA81898)
val md_theme_dark_surfaceTint = Color(0xFFFFACEA)
val md_theme_dark_surfaceTintColor = Color(0xFFFFACEA)


val seed = Color(0xFF9D048F)
